[package]
name = "project-life"
version = "0.1.0"
description = "Project Life — notes, schedule, tasks, habits and goals"
authors = ["UltimaBass"]
edition = "2021"

[lib]
name = "project_life_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-window-state = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.45"
base64 = "0.23.1"
percent-encoding = "2.3.2"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
ureq = { version = "3", features = ["platform-verifier"] }
url = "2.5.8"
regex = "1.13.1"
windows = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_System_Diagnostics_ToolHelp", "Devices_Geolocation", "Foundation", "Win32_System_Time"] }
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2"
tauri-winrt-notification = "0.7"
keyring = { version = "3", features = ["windows-native"] }
tauri-plugin-autostart = "2"
getrandom = "0.3"
sha2 = "0.10"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
