[package]
name = "project-life"
version = "0.1.0"
description = "Project Life — notes, schedule, tasks, habits and goals"
authors = ["UltimaBass"]
edition = "2021"

[lib]
name = "project_life_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-window-state = "2"
tauri-plugin-opener = "2"
ureq = { version = "3", features = ["platform-verifier"] }
url = "2.5.8"
regex = "1.13.1"
windows = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
