import {
  AArrowDown,
  AArrowUp,
  Archive,
  ArrowDown,
  ArrowUp,
  Bell,
  Bold,
  BookOpen,
  CircleCheck,
  ClipboardPaste,
  Code,
  CornerDownRight,
  IndentDecrease,
  IndentIncrease,
  Copy,
  EyeOff,
  FileDown,
  FilePlus,
  FileUp,
  FolderInput,
  FolderOpen,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  House,
  Info,
  Italic,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  Minus,
  PanelLeft,
  Pencil,
  Pilcrow,
  Pin,
  Quote,
  RefreshCw,
  Save,
  Scissors,
  Settings,
  Siren,
  Smile,
  SquareCode,
  Strikethrough,
  Table2,
  Tag,
  Tags,
  TextSelect,
  Trash2,
  TriangleAlert,
  Underline,
  X,
  type LucideIcon,
} from "lucide-react";
import type { ReactNode } from "react";

// One icon per command, so a command looks the same in every menu it's in:
// the title bar menus, right-click menus and the block menu. The menus draw
// them at their own size (index.css: .menu-icon).
export const commandIcons: Record<string, LucideIcon> = {
  "app.new": FilePlus,
  "app.newPage": CornerDownRight,
  "app.movePage": FolderInput,
  "app.noteUp": ArrowUp,
  "app.noteDown": ArrowDown,
  "app.noteIn": IndentIncrease,
  "app.noteOut": IndentDecrease,
  "app.rename": Pencil,
  "app.pin": Pin,
  "app.tag": Tag,
  "app.tags": Tags,
  "app.import": FileDown,
  "app.save": Save,
  "app.reload": RefreshCw,
  "app.export": FileUp,
  "app.exportAll": Archive,
  "app.notesFolder": FolderOpen,
  "app.recycle": Trash2,
  "app.delete": X,
  "app.bin": Trash2,
  "app.emoji": Smile,
  "app.home": House,
  "app.sidebar": PanelLeft,
  "app.tasks": ListTodo,
  "app.larger": AArrowUp,
  "app.smaller": AArrowDown,
  "app.settings": Settings,
  "app.guide": BookOpen,
  "app.about": Info,
  "markdown.Bold": Bold,
  "markdown.Italic": Italic,
  "markdown.Underline": Underline,
  "markdown.Strikethrough": Strikethrough,
  "markdown.Inline code": Code,
  "markdown.Spoiler": EyeOff,
  "markdown.Link": Link2,
  "markdown.Paragraph": Pilcrow,
  "markdown.Heading 1": Heading1,
  "markdown.Heading 2": Heading2,
  "markdown.Heading 3": Heading3,
  "markdown.Heading 4": Heading4,
  "markdown.Heading 5": Heading5,
  "markdown.Heading 6": Heading6,
  "markdown.Bullet list": List,
  "markdown.Numbered list": ListOrdered,
  "markdown.Task list": ListChecks,
  "markdown.Blockquote": Quote,
  "markdown.Code block": SquareCode,
  "markdown.Table": Table2,
  "markdown.Divider": Minus,
  "markdown.Info": Info,
  "markdown.Notification": Bell,
  "markdown.Alert": TriangleAlert,
  "markdown.Success": CircleCheck,
  "markdown.Emergency": Siren,
  "block.up": ArrowUp,
  "block.down": ArrowDown,
};

export function commandIcon(id: string): ReactNode {
  const Icon = commandIcons[id];
  return Icon ? <Icon size={15} /> : undefined;
}

// Callouts by kind, each in its own color.
const calloutIcons: Record<string, LucideIcon> = {
  info: Info,
  notification: Bell,
  alert: TriangleAlert,
  success: CircleCheck,
  emergency: Siren,
};

export function calloutIcon(kind: string, color?: string): ReactNode {
  const Icon = calloutIcons[kind.toLowerCase()] ?? Info;
  return <Icon size={15} style={color ? { color } : undefined} />;
}

// Cut, copy, paste and select all, for every text field's menu.
export const clipboardIcons = {
  cut: <Scissors size={15} />,
  copy: <Copy size={15} />,
  paste: <ClipboardPaste size={15} />,
  selectAll: <TextSelect size={15} />,
};
